### ISSUE TITLE
Kind level procedures still require a uuid

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#133]
Even though the URL description in the yaml does not require a uuid, it is still required by the api call.

![Screen Shot 2019-05-22 at 2 35 09 PM](https://user-images.githubusercontent.com/39283673/58210649-e169e000-7c9e-11e9-889a-5c976789334c.png)

**Comment by shlomi-nx** [comment]
This is the part that is generated:
```yaml
 /services/xi_clusters/0.0.1/imaged_cluster/procedure/create_aws_cluster:
    post:
      description: Calls a procedure create_aws_cluster
      operationId: callxi_clusterscreate_aws_cluster
      tags:
        - xi_clusters/0.0.1/imaged_cluster/procedure
      parameters:
        - name: uuid
          in: path
          description: UUID of the entity
          required: true
          schema:
            type: string
            format: uuid
```
