### ISSUE TITLE
Swagger - status-only fields are presented as spec fields

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#161]
If we have an kind such as:
```yaml
test_kind:
  type: object
  x-papiea-entity: spec-only
  properties:
    status_field:
      x-papiea: status-only
      type: string
```

In the swagger ui for `POST` (creation) I am seeing:
```json
{
  "spec": {
    "status_field": "string"
   }
}
```

Instead of an empty spec (in this case)
