### ISSUE TITLE
When defining a kind, change default attribute status-only/intentful assignment

### ISSUE THREAD

**Issue by shlomi-nx** [nutanix/papiea-js#371]
Currently, when specifying a kind model for a `differ` kind (we should probably rename this to `intentful`), a field is `intentful` by default (meaning it exists in both spec and status), and the user can make it `status-only` by specifying this on the individual fields.

I was asked if we can inverse that, if we can only specify `intentful` on relevant fields and have the rest be `status-only` by default.

I suppose we could do this by introducing another top-level directive:
```
...
x-papiea-entity: differ // Should be `intentful`
x-papiea-default: status-only
 properties:
    so-field:
      type: string
      description: implicitly status-only-field
    i-field:
      type: string
      x-papiea: intentful
      description: intentful field
```

If `x-papiea-default` is omitted, the behavior remains as it currently is.
